<div class="row">    
    <div class="col-lg-12 text-center">        
        <h3 class="text-danger">Acesso Negado</h3>
        <?php if ($this->typeDeny == 1) : ?>        
        <p>Desculpe, você não tem permissão para visualizar esta página.</p>
        <?php else : ?>
        <p>Desculpe, o seu plano não contempla a visualização desta página.</p>
        <?php endif; ?>
        <p>Obrigado.</p>
    </div>
</div>