<div class="row">    
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">
                Meus Cartões
                <div class="pull-right">
                    <a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'cartoes',
                        'action' => 'novo-cartao'
                    ), null, true); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/icon_add.png'); ?>" width="25px" title="Cadastrar Cartão"/>
                        <span class="text-info">Novo Cartão</span>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="bg-success"><a href="#ativo" role="tab" data-toggle="tab"><span class="text-success">Cartões Ativos</span></a></li>
                    <li class="bg-danger"><a href="#inativo" role="tab" data-toggle="tab"><span class="text-danger">Cartões Inativos</span></a></li>                  
                </ul>
                
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="ativo">  
                        <?php if ($this->cartoes_ativos->count() > 0) : ?>
                        <table class="table table-striped table-responsive">
                            <tr>
                                <th class="text-center">Bandeira</th>
                                <th>Descrição</th>
                                <th class="text-right">Limite</th>
                                <th class="text-center">Fechamento</th>
                                <th class="text-center">Vencimento</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            <?php foreach ($this->cartoes_ativos as $cartao) : ?>
                            <tr>
                                <td class="text-center"><?php echo View_Helper_Cartoes::getBandeiraCartao($cartao->bandeira_cartao); ?></td>
                                <td><?php echo $cartao->descricao_cartao; ?></td>
                                <td class="text-right"><?php echo View_Helper_Currency::getCurrency($cartao->limite_cartao); ?></td>
                                <td class="text-center">Dia <?php echo $cartao->fechamento_cartao; ?></td>
                                <td class="text-center">Dia <?php echo $cartao->vencimento_cartao; ?></td>
                                <td class="text-center">
                                    <a href="<?php echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'cartoes',
                                        'action' => 'editar-cartao',
                                        'id_cartao' => $cartao->id_cartao
                                    )); ?>">
                                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" width="20" title="Editar" />
                                    </a>
                                    <a href="<?php echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'cartoes',
                                        'action' => 'excluir-cartao',
                                        'id_cartao' => $cartao->id_cartao
                                    )); ?>">
                                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" width="20" title="Excluir" />
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        <?php else : ?>
                        <div class="text-warning">Nenhum registro</div>
                        <?php endif; ?>
                    </div>
                    <div class="tab-pane fade" id="inativo">
                        <?php if ($this->cartoes_inativos->count() > 0) : ?>
                        <table class="table table-striped table-responsive">
                            <tr>
                                <th class="text-center">Bandeira</th>
                                <th>Descrição</th>
                                <th class="text-right">Limite</th>
                                <th class="text-center">Fechamento</th>
                                <th class="text-center">Vencimento</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            <?php foreach ($this->cartoes_inativos as $cartao) : ?>
                            <tr>
                                <td class="text-center"><?php echo View_Helper_Cartoes::getBandeiraCartao($cartao->bandeira_cartao); ?></td>
                                <td><?php echo $cartao->descricao_cartao; ?></td>
                                <td class="text-right"><?php echo View_Helper_Currency::getCurrency($cartao->limite_cartao); ?></td>
                                <td class="text-center">Dia <?php echo $cartao->fechamento_cartao; ?></td>
                                <td class="text-center">Dia <?php echo $cartao->vencimento_cartao; ?></td>
                                <td class="text-center">
                                    <a href="<?php echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'cartoes',
                                        'action' => 'reativar-cartao',
                                        'id_cartao' => $cartao->id_cartao
                                    )); ?>">
                                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_reativar.png'); ?>" width="20" title="Reativar Cartão" />
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        <?php else : ?>
                        <div class="text-warning">Nenhum registro</div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
