<div class="row">    
    <div class="col-lg-2"></div>
    <div class="col-lg-8">    
        <p class="text-red bg-danger text-center padding-10px">
            <label>Tem certeza que deseja excluir esse lançamento?</label>
        </p>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-2 bold text-center">Data</div>
                    <div class="col-lg-4 bold">Descrição</div>
                    <div class="col-lg-1 bold text-right">Valor</div>
                </div>
                <div class="row">
                    <div class="col-lg-2 text-center"><?php echo View_Helper_Date::getDataView($this->dadosMovimentacao->data_movimentacao); ?></div>
                    <div class="col-lg-4"><?php echo $this->dadosMovimentacao->descricao_movimentacao; ?></div>
                    <div class="col-lg-1 text-right"><?php echo View_Helper_Currency::getCurrency($this->dadosMovimentacao->valor_movimentacao); ?></div>
                </div>        
            </div>
        </div>
        <form method="post" class="form-group">
            <?php if ($this->id_movimentacao_pai) : ?>
            <p class="text-blue">Esse lançamento se repete. O que deseja fazer?</p>
            <div class="radio">
                <label>
                    <input type="radio" name="opt-delete" value="0" checked />
                    Excluir somente essa
                </label>                                
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="opt-delete" value="1" />
                    Excluir essa e as anteriores <span class="small small text-red">cuidado ao escolher esta opção!</span>
                </label>                                
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="opt-delete" value="2" />
                    Excluir essa e as posteriores <span class="small small text-red">cuidado ao escolher esta opção!</span>
                </label>                                
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="opt-delete" value="3" />
                    Excluir todas <span class="small small text-red">cuidado ao escolher esta opção!</span>
                </label>                                
            </div>
            <?php endif; ?>
            <p class="lancamento">
                <input type="submit" class="btn btn-success" name="btnResposta" value="Sim Apagar" />
                <input type="submit" class="btn btn-danger" name="btnResposta" value="Cancelar" />
            </p>        
        </form>        
    </div>
    <div class="col-lg-2"></div>
</div>