<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/cliente/movimentacoes/nova-despesa.js')); ?>
<div class="row">    
    <div class="col-lg-12">    
        <div class="panel panel-danger">
            <div class="panel-heading">Nova Despesa</div>
            <div class="panel-body">                
                <div class="col-lg-4">
                    <?php echo $this->formMovimentacoesDespesa; ?>
                </div>
                <div class="col-lg-8">
                    
                </div>
            </div>
        </div>
    </div>
</div>