<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/movimentacoes/transferencia.js')); ?>
<div class="row">    
    <div class="col-lg-12">    
        <div class="panel panel-info">
            <div class="panel-heading">Transferência</div>
            <div class="panel-body">                
                <div class="col-lg-4">
                    <?php echo $this->formMovimentacaoTransferencia; ?>
                </div>
                <div class="col-lg-8">
                    
                </div>
            </div>
        </div>
    </div>
</div>