<div class="row">
    <div class="col-lg-12">
        <?php echo View_Helper_Messages::render($this->messages); ?>
        <div class="panel panel-info">
            <div class="panel-heading">Novo Chamado</div>
            <div class="panel-body">
                <div class="col-lg-4">
                    <?php echo $this->formChamado; ?>
                </div>                
            </div>
        </div>
    </div>
</div>

