<div class="row">
    <div class="col-lg-12">        
        <?php echo View_Helper_Messages::render($this->messages, $this->alerts); ?>
        <div class="panel panel-info">
            <div class="panel-heading">
                <span class="text-info">Editar categoria</span> 
            </div>
            <div class="panel-body">
                <div class="col-lg-6">
                    <?php echo $this->formCategoriaCadastro; ?>
                </div>
            </div>
        </div>
    </div>
</div>