<div class="row">
    <div class="col-lg-12">        
        <?php echo View_Helper_Messages::render($this->messages, $this->alerts); ?>
        <div class="panel panel-info">
            <div class="panel-heading">
                <span class="text-info">Categorias</span> 
                <div class="pull-right">
                    <a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'categorias',
                        'action' => 'nova-categoria'
                    ), null, true); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/icon_add.png'); ?>" width="25px" title="Cadastrar Orçamento"/> 
                        <span class="text-info">Nova Categoria</span>
                    </a>
                </div>
            </div>
            <div class="panel-body">  
                <table class="table table-striped table-responsive">
                    <tr>
                        <th>Categoria</th>
                        
                        <th>Tipo</th>
                        <th class="col-md-2">Ações</th>                                                
                    </tr>
                    <?php if ($this->categorias->count() > 0) : ?>
                    <?php foreach ($this->categorias as $categoria) : ?>
                    <tr>
                        <td>
                            <?php echo $categoria->descricao_categoria; ?>
                            <?php if ($categoria->id_categoria_pai) : ?>
                            <span class="text-warning"> >> </span><?php echo $categoria->descricao_categoria_pai; ?>
                            <?php endif; ?>
                        </td>                        
                        <td><?php echo $categoria->id_usuario ? "<span class='text-success'>Usuário</span>" : "<span class='text-info'>Sistema</span>"; ?></td>                        
                        <td>
                            <?php if ($categoria->id_usuario) : ?>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'categorias',
                                'action' => 'editar',
                                'id_categoria' => $categoria->id_categoria
                            ), null, true); ?>" class="btn btn-sm btn-info">Editar</a>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'categorias',
                                'action' => 'excluir',
                                'id_categoria' => $categoria->id_categoria
                            ), null, true); ?>" class="btn btn-sm btn-danger">Excluir</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    <?php else : ?>
                    <?php endif; ?>
                </table>
            </div>
        </div>
    </div>
</div>

