<?php $identity = Zend_Auth::getInstance()->hasIdentity(); ?>
<?php $auth = Zend_Auth::getInstance()->getIdentity(); ?>
<?php

    $namePart = explode(" ", $auth->nome_completo);    
    foreach ($namePart as $key => $value) {
        $short_name = $namePart[0] . ' ';        
        if ($key + 1 == count($namePart)) {
            $short_name .= $value;
        }
    }

?>

<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for layout -->
        <link href="<?php echo $this->baseUrl('views/css/layout.css'); ?>" rel="stylesheet">
        <!-- Custom datepicker -->
        <link href="<?php echo $this->baseUrl('views/css/datepicker.css'); ?>" rel="stylesheet">
        <!-- Custom timeline -->
        <link href="<?php echo $this->baseUrl('views/css/timeline.css'); ?>" rel="stylesheet">        
        
        <script src="<?php echo $this->baseUrl("views/js/jquery-1.10.2.js"); ?>"></script>        
        <script src="<?php echo $this->baseUrl('views/js/highcharts/highcharts.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('views/js/highcharts/modules/exporting.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('views/js/bootstrap-datepicker.js'); ?>"></script>        
        <script src="<?php echo $this->baseUrl('views/js/jquery.maskMoney.js'); ?>"></script>                
        <script src="<?php echo $this->baseUrl('views/js/jquery.maskedinput.js'); ?>"></script>                                   
        <script src="<?php echo $this->baseUrl('views/js/application.js'); ?>"></script>     
        <script src="<?php echo $this->baseUrl('views/js/bootstrap.js'); ?>"></script>  
    </head>

    <body id="body" class="background-color-snow">
        <nav class="navbar navbar-default navbar-fixed-top background-color-blue" role="navigation">
            <div class="container container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">MENU</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">                    
                        <li class=""><a href="<?php
                            echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'index',
                                'action' => 'index'
                            ), null, true);
                            ?>"><span class="glyphicon glyphicon-home"></span> Início</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-share"></span> Lançamentos <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'movimentacoes',
                                    'action' => 'nova-receita'
                                ), null, true); ?>"><span class="glyphicon glyphicon-arrow-right"></span> Nova Receita</a></li>
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'movimentacoes',
                                    'action' => 'nova-despesa'
                                ), null, true); ?>"><span class="glyphicon glyphicon-arrow-left"></span> Nova Despesa</a></li>
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'movimentacoes',
                                    'action' => 'transferencia'
                                ), null, true); ?>"><span class="glyphicon glyphicon-transfer"></span> Transferência</a></li>
                            </ul>
                        </li>
                        <!--
                        <li class="active"><a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'orcamentos',
                            'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-list-alt"></span> Orçamentos</a></li>
                        <!--
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-list"></span> Relatórios <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array()); ?>">Anual</a></li>
                            </ul>
                        </li>
                        -->
                        <!--
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-credit-card"></span> Contas/Cartão <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'contas',
                                    'action' => 'index'
                                ), null, true); ?>"><span class="glyphicon glyphicon-list"></span> Minhas Contas</a></li>
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'contas',
                                    'action' => 'nova-conta'
                                ), null, true); ?>"><span class="glyphicon glyphicon-record"></span> Nova Conta</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'cartoes',
                                    'action' => 'index'
                                ), null, true); ?>"><span class="glyphicon glyphicon-list"></span> Meus Cartões</a></li>
                                <li><a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'cartoes',
                                    'action' => 'novo-cartao'
                                ), null, true); ?>"><span class="glyphicon glyphicon-record"></span> Novo Cartão</a></li>
                            </ul>
                        </li>
                        <li class="active"><a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'chamados',
                            'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-comment"></span> Meus Chamados</a></li>

                        <li class="active"><a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'chamados',
                            'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-pencil"></span> FAQ</a></li>
                        -->
                    </ul>               
                    <ul class="nav navbar-nav navbar-right">        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">                
                                <span class="glyphicon glyphicon-user"></span> <?php echo $short_name; ?> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php
                                    echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'meusdados',
                                        'action' => 'index'
                                    ), null, true);
                                    ?>"><span class="glyphicon glyphicon-cog"></span> Configurações</a></li>                    
                                <li class="divider"></li>
                                <li><a href="<?php
                                    echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'usuarios',
                                        'action' => 'logout'
                                    ), null, true);
                                    ?>"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
                            </ul>
                        </li>
                    </ul>                                        
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>    
        <div class="container container-fluid" style="margin-top: 80px;"> 
            <!--
            <div class="col-lg-7"></div>
            <div class="col-lg-3 small text-right">
                
                Ajude-nos a manter este sistema
                <p>Faça uma doação.</p>
            </div>
            <div class="col-lg-2">
                <div class="pull-right">
                    <form action="https://pagseguro.uol.com.br/checkout/v2/donation.html" method="post" target="_blank">
                        
                        <input type="hidden" name="currency" value="BRL" />
                        <input type="hidden" name="receiverEmail" value="nandorodpires@gmail.com" />
                        <input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/doacoes/164x37-doar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
                    </form>
                </div>
            </div>
            -->
                        
            <div class="col-lg-12 col-sm-12">
                <?php //echo $this->partial("partials/breadcrumbs.phtml"); ?>
                <?php echo $this->layout()->content; ?>                    
            </div>             
        </div>
        <footer class="background-color-orange">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <a class="redes-sociais" href="https://www.facebook.com/sisnewfinances" target="_blank">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_face_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="https://twitter.com/NewFinances" target="_blank">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_twitter_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="https://plus.google.com/104418631172971802903/posts" target="_blank">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_google_plus_social2.png'); ?>" />
                        </a>
                    </div>                                                                          
                </div>   
            </div>            
        </footer>
        <!-- /container -->
    </body>

</html>


