<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-1.10.2.js')); ?>              
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap-datepicker.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskMoney.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskedinput.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/application.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap.js')); ?>  
                
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for layout -->
        <link href="<?php echo $this->baseUrl('views/css/layout.css'); ?>" rel="stylesheet">
        <!-- Custom timeline -->
        <link href="<?php echo $this->baseUrl('views/css/timeline.css'); ?>" rel="stylesheet">   
        <!-- Custom themes -->
        <link href="<?php echo $this->baseUrl('views/css/themes.css'); ?>" rel="stylesheet">   
        
    </head>

    <body id="body" class="">
        <nav class="navbar navbar-default navbar-fixed-top background-color-blue" role="navigation">
            <div class="container container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">MENU</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'mobile',
                                'controller' => 'index',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-home"></span> Início</a></li>                               
                       
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'mobile',
                                'controller' => 'contato',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-user"></span> Faça Contato</a></li>                             
                    </ul>                    
                    <div class="navbar-form navbar-right">
                        <a class="btn btn-sm btn-success" href="<?php echo $this->url(array(
                                'module' => 'mobile',
                                'controller' => 'cadastro-usuario',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-new-window"></span> Cadastre-se</a>
                        <a class="btn btn-sm btn-info" href="<?php echo $this->url(array(
                                'module' => 'mobile',
                                'controller' => 'usuarios',
                                'action' => 'login'
                        ), null, true); ?>"><span class="glyphicon glyphicon-log-in"></span> Acesse o sistema</a>
                    </div>                                        
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>           
        
        <nav class="navbar" style="margin-bottom: -5px;" role="navigation">  
            
            <div class="background-color-white">                
                <div class="container container-fluid container-logo">
                    <img class="img img-responsive margin-10px-0px" src="<?php echo $this->baseUrl('views/img/logo_newfinances.png'); ?>" width="150"/>            
                </div>
            </div>
        </nav> 
        
        <div class="container container-fluid">            
            <div class="row">
                <div class="col-lg-12 background-color-white">    
                    <hr />
                    <?php echo $this->layout()->content; ?>                    
                </div>           
            </div>
        </div>
        
        <footer class="background-color-orange">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <a class="redes-sociais" href="https://www.facebook.com/sisnewfinances" target="_blank">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_face_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="https://twitter.com/NewFinances" target="_blank">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_twitter_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="https://plus.google.com/104418631172971802903/posts" target="_blank">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_google_plus_social2.png'); ?>" />
                        </a>
                    </div>                                                                          
                </div>   
            </div>            
        </footer>
        <!-- /container -->
    </body>
    <div id="fb-root"></div>    
</html>


