<div class="col-lg-12">
    <div class="row">
        <div class="col-lg-12"><h4 class="text-success">O que você encontra no NewFinances</h4></div>
        <ul class="timeline" style="margin: 0">
            <li> 
                <div class="timeline-badge"><i class="glyphicon"></i></div> 
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <p>                        
                            <small class="text-muted">bla bla</small>
                            <small class="text-muted">bla bla</small>
                        </p>
                        <h4 class="timeline-title">bla bla</h4>                    
                    </div> 
                    <div class="timeline-body">bla bla bla</div>
                </div>
            </li>        
            <li class="timeline-inverted">  
                <div class="timeline-badge"><i class="glyphicon"></i></div> 
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <p>                        
                            <small class="text-muted">bla bla</small>
                            <small class="text-muted">bla bla</small>
                        </p>
                        <h4 class="timeline-title">bla bla</h4>                    
                    </div> 
                    <div class="timeline-body">bla bla bla</div>
                </div>
            </li>
        </ul>
    </div>
</div>