<div class="row margin-10px">    
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">Alterar senha</div>
            <div class="panel-body">            
                <div class="col-lg-5">
                    <?php echo $this->formAlterarSenha; ?>
                </div>
                <div class="col-lg-7"></div>
            </div>
        </div>
    </div>
</div>