<html>
    <body>
        <div style="float: left; width: 70%; margin: 10px 15%; border: 1px solid #696969; padding: 0 7px;">
            <div style="float: left; width: 100%;">
                <img style="padding: 15px; width: 250px;" src="http://newfinances.com.br/views/img/logo_newfinances.png" />
                <div style="float: left; width: 100%; padding: 7px;">
                    <h2 style="text-align: center; margin: 10px 0;">Usuário Cadastrado</h2 >
                    <p>Olá <?php echo $this->nome_completo; ?></p>
                    <p>Seu cadastro foi realizado com sucesso! Seja Bem vindo ao NewFinances</p>                
                </div>
            </div>
            <div>
                <p>Acesse o link abaixo para ativar sua conta: </p>                
                <p><a href="<?php echo $this->url_ativar; ?>">Ativar Minha Conta</a></p>                
            </div>
            <div style="position: relative; bottom: 0; left: 0;">
                <p style="text-align: center;">E-mail gerado automaticamente. Por favor não responda ao mesmo.</p>
                <p style="font-size: 12px; margin-top: 13px;">Atenciosamente,</p>
                <p style="font-weight: bold; font-size: 12px; margin-bottom: 7px;">Equipe NewFinances - contato@newfinances.com.br</p>        
            </div>
        </div>
    </body>
</html>