<div class="row">
    <div class="col-lg-12">
        <h5 class="small"><?php echo $this->data_movimentacao; ?></h5>
    </div>
</div>
<?php if ($this->movimentacoes->count() > 0) : ?>
<div class="row">    
    <?php foreach ($this->movimentacoes as $movimentacao) : ?>
    <div class="col-lg-12 small <?php echo View_Helper_Movimentacao::getClassRowMovimentacao($movimentacao->id_tipo_movimentacao); ?>">
        <?php echo $movimentacao->descricao_movimentacao; ?>
        <?php if ($movimentacao->id_movimentacao_pai) : ?>
        <span class="glyphicon glyphicon-repeat"></span>
        <?php endif; ?>
        <?php if ($movimentacao->id_tipo_movimentacao == 3) : ?>
            <p class="small text-muted"><?php echo $movimentacao->descricao_cartao; ?></p>
        <?php elseif ($movimentacao->id_tipo_movimentacao == 4) : ?>
            <p class="small text-muted">De <?php echo $movimentacao->descricao_conta; ?> para <?php echo $movimentacao->descricao_conta_destino; ?></p>                
        <?php else : ?>
            <p class="small text-muted"><?php echo $movimentacao->descricao_conta; ?></p>
        <?php endif; ?>
    </div>    
    <div class="col-lg-12 small">
        <hr />
    </div>
    <?php endforeach; ?>        
</div>
<?php else : ?>
    
<?php endif; ?>