<div class="row">    
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">
                Minhas Contas
                <div class="pull-right">
                    <a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'contas',
                        'action' => 'nova-conta'
                    ), null, true); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/icon_add.png'); ?>" width="25px" title="Cadastrar Conta"/>
                        <span class="text-info">Nova Conta</span>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="bg-success"><a href="#ativo" role="tab" data-toggle="tab"><span class="text-success">Contas Ativas</span></a></li>
                    <li class="bg-danger"><a href="#inativo" role="tab" data-toggle="tab"><span class="text-danger">Contas Inativas</span></a></li>                  
                </ul>
                
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="ativo">                    
                        <?php if ($this->contas_ativas->count() > 0) : ?>
                        <table class="table table-striped table-responsive">
                            <tr>
                                <th>Banco</th>
                                <th>Descrição</th>
                                <th>Tipo</th>                        
                                <th class="text-right">Saldo Inicial</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            <?php foreach ($this->contas_ativas as $conta) : ?>
                            <tr>
                                <td>
                                    <?php if ($conta->logo_banco) : ?>
                                    <img class="img" src="<?php echo $this->baseUrl('views/img/bancos/' . $conta->logo_banco); ?>" width="17px" />
                                    <?php else : ?>
                                    <img class="img" src="<?php echo $this->baseUrl('views/img/bancos/icon_no.png'); ?>" width="17px" />
                                    <?php endif; ?>
                                    <?php echo $conta->nome_banco ? $conta->nome_banco : 'Nenhum'; ?>
                                </td>
                                <td><?php echo $conta->descricao_conta; ?></td>
                                <td><?php echo $conta->descricao_tipo_conta; ?></td>                        
                                <td class="text-right"><?php echo View_Helper_Currency::getCurrency($conta->saldo_inicial); ?></td>                                                        
                                <td class="text-center">
                                    <a href="<?php echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'contas',
                                        'action' => 'editar-conta',
                                        'id_conta' => $conta->id_conta
                                    )); ?>">
                                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" width="20" title="Editar" />
                                    </a>
                                    <a href="<?php echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'contas',
                                        'action' => 'excluir-conta',
                                        'id_conta' => $conta->id_conta
                                    )); ?>">
                                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" width="20" title="Excluir" />
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        <?php else : ?>
                        <div class="text-warning padding-10px-0">Nenhum registro</div>
                        <?php endif; ?>
                    </div>  
                    <div class="tab-pane fade" id="inativo">
                        <?php if ($this->contas_inativas->count() > 0) : ?>
                        <table class="table table-striped table-responsive">
                            <tr>
                                <th>Banco</th>
                                <th>Descrição</th>
                                <th>Tipo</th>                        
                                <th class="text-right">Saldo Inicial</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            <?php foreach ($this->contas_inativas as $conta) : ?>
                            <tr>
                                <td>
                                    <?php if ($conta->logo_banco) : ?>
                                    <img class="img" src="<?php echo $this->baseUrl('views/img/bancos/' . $conta->logo_banco); ?>" />
                                    <?php else : ?>
                                    <img class="img" src="<?php echo $this->baseUrl('views/img/bancos/icon_no.png'); ?>" />
                                    <?php endif; ?>
                                    <?php echo $conta->nome_banco ? $conta->nome_banco : 'Nenhum'; ?>
                                </td>
                                <td><?php echo $conta->descricao_conta; ?></td>
                                <td><?php echo $conta->descricao_tipo_conta; ?></td>                        
                                <td class="text-right"><?php echo View_Helper_Currency::getCurrency($conta->saldo_inicial); ?></td>                        
                                <td class="text-center">
                                    <a href="<?php echo $this->url(array(
                                        'module' => 'cliente',
                                        'controller' => 'contas',
                                        'action' => 'reativar-conta',
                                        'id_conta' => $conta->id_conta
                                    )); ?>">
                                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_reativar.png'); ?>" width="20" title="Reativar Conta" />
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        <?php else : ?>
                        <div class="text-warning padding-10px-0">Nenhum registro</div>
                        <?php endif; ?>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>