<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/cliente/contas/nova-conta.js')); ?>
<div class="row">    
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">Nova Receita</div>
            <div class="panel-body">                
                <div class="col-lg-4">
                    <?php echo $this->formClienteConta; ?>
                </div>     
            </div>
        </div>
    </div>
</div>